#! /bin/sh
### BEGIN INIT INFO
# Provides:          asplashscreen
# Required-Start:
# Required-Stop:
# Should-Start:      
# Default-Start:     S
# Default-Stop:
# Short-Description: Show custom splashscreen
# Description:       Show custom splashscreen
### END INIT INFO

do_start () {

    /usr/bin/fbi -T 1 -noverbose -a /var/thinclient/splashscreen.png    
    exit 0
}

case "$1" in
  start|"")
    do_start
    ;;
   restart|reload|force-reload)
    echo "Error: argument '$1' not supported"
    exit 3
    ;;
  stop)
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: asplashscreen [start|stop]"
    exit 3
    ;;
esac
